# Generated by Django 5.2.7 on 2025-10-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0004_branch_section_year_alter_student_s_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('f_fname', models.CharField(max_length=20)),
                ('f_lname', models.CharField(max_length=20)),
                ('f_subject', models.CharField(max_length=50)),
                ('f_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyView.branch')),
            ],
        ),
    ]
